### PR TITLE
Windows SDK v2.0.8 update

### PR DESCRIPTION
**Pull request by DavidKimVungle**
Added more examples and cleaned up deprecated message. @nikitalucenko Can you do a code review and push the code to Vungle/Windows-SDK after creating a new branch "sdk2"?

### CODE REVIEW

**Comment by DavidKimVungle** [comment]
@nikitalucenko @kosyakow Can someone do a code review for the minor changes and comments added, and then push this over to Vungle/Windows-SDK repo?

**Comment by nikitalucenko** [comment]
@DavidKimVungle 

> Added more examples

I can't see new examples in your commits. I see fixes for Windows 10 universal c# sample. 
Should I apply this fixes for all other samples (Windows 8 c# and c++, Windows 8 phone c# and c++, Windows 10 universal c++, DirectX and visual basic)? Please let me know if i misunderstood you.

**Comment by DavidKimVungle** [comment]
@nikitalucenko I have only updated Windows 10 C# sample as I was time pressed for the release. It would be very nice if you can work on the C# projects, C++, DirectX and VB and push it to Vungle/Windows-SDK.

Have you been working on sample code for v2.1 for native ad integration? If so, it would be great if you can share the repo with me.

**Comment by nikitalucenko** [comment]
@DavidKimVungle I created new pull request to Vungle/Windows-SDK to master branch.

**Pull request merged**
